/*
 * This source file was generated by the Gradle 'init' task
 */
package org.APCSLowell;

public class GoogleBillboard {
public boolean isPrime(long num)  
{   
   if(num<2){
    return false;
  }
  if(num==2)
    return true;
  for(int i=2;i<(int)(Math.sqrt(num)+1);i++){
    if(num%i==0){
      return false;
    }
  }
  return true; 

      
    }
    public long firstPrimeNumberIn(String e) {
        int i=0;
    while(true){
  String d=e.substring(i,i+10);
  Long num =Long.parseLong(d);
  if(isPrime(num)){
    return(num);
  }
  i++;
}
  
    
    }
}
